### ISSUE TITLE
Make Nav Bar Fixed

### ISSUE THREAD

**Issue by Sukriti-sood** [vigneshshettyin/vigneshshettyin#1]
In Website

**Comment by vigneshshettyin** [comment]
> In Website

Hey, @Sukriti-sood in which site do you want to fix the navbar of my portfolio I didn't get you?

**Comment by Sukriti-sood** [comment]
> > In Website
> 
> Hey, @Sukriti-sood in which site do you want to fix the navbar of my portfolio I didn't get you?

Sorry ,But Ya, I was giving suggestion for ur portfolio.

**Comment by vigneshshettyin** [comment]
> > > In Website
> > 
> > 
> > Hey, @Sukriti-sood in which site do you want to fix the navbar of my portfolio I didn't get you?
> 
> Sorry ,But Ya, I was giving suggestion for ur portfolio.

Hey, @Sukriti-sood you can give suggestions no issues. Post it here by raising an issue here(https://github.com/vigneshshettyin/Portfolio).

**Comment by Sukriti-sood** [comment]
@vigneshshettyin  Ook..
